recipe_name_text = 'Мой новый рецепт'
product_name_text = 'Мой новый продукт'
ingredient_group_name = 'Вода и напитки'
ingredient_name_text = 'Боржоми'
calories, squirrels, fats, carbohydrates = '11', '14', '15', '18'
